// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ArtifactView = { kind: string, media_type: string, byte_length: number, sha256: string, sample_rate: number, channels: number, };
