// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClientMessage = { "t": "hello", v: number, id: string, pubkey: string, pair_proof?: string, } | { "t": "auth", v: number, id: string, sig: string, } | { "t": "status", v: number, id: string, };
