// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenerationRequest } from "./GenerationRequest";
import type { JobState } from "./JobState";

export type ClientMessage = { "t": "hello", v: number, id: string, pubkey: string, pair_proof?: string, petname?: string, } | { "t": "auth", v: number, id: string, sig: string, } | { "t": "status", v: number, id: string, } | { "t": "job.create", v: number, id: string, client_request_id: string, model: string, generation: GenerationRequest, } | { "t": "jobs.list", v: number, id: string, states?: Array<JobState>, cursor?: string, limit?: number, } | { "t": "job.get", v: number, id: string, job_id: string, };
