// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ErrorCode = "unsupported_version" | "unauthenticated" | "rejected" | "invalid_request" | "not_found" | "model_not_installed" | "model_unavailable" | "idempotency_conflict" | "queue_full" | "insufficient_disk" | "temporarily_unavailable" | "feature_unavailable" | "internal";
