// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ErrorDetails = { "kind": "supported_version", minimum: number, maximum: number, } | { "kind": "invalid_field", field: string, } | { "kind": "model", selector: string, } | { "kind": "correlation", correlation_id: string, };
