// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobView } from "./JobView";
import type { SongHeader } from "./SongHeader";

export type ErrorDetails = { "kind": "supported_version", minimum: number, maximum: number, } | { "kind": "invalid_field", field: string, } | { "kind": "model", selector: string, } | { "kind": "correlation", correlation_id: string, } | { "kind": "revision_conflict", current: SongHeader, } | { "kind": "job_revision_conflict", current: JobView, } | { "kind": "job_state", current: JobView, } | { "kind": "full_sync", minimum_revision: number, };
