// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParameterValue } from "./ParameterValue";

export type GenerationRequest = { caption: string, lyrics?: string, duration?: number, steps?: number, cfg?: number, seed?: number | undefined, 
/**
 * Values for the parameters the selected model declared.
 *
 * Empty for an old client, and for a model that declares nothing. A field
 * supplied here *and* through a legacy top-level field is rejected rather
 * than resolved by precedence: silently picking one would run a generation
 * the caller did not ask for.
 */
extensions?: { [key in string]: ParameterValue }, };
