// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProgressUnit } from "./ProgressUnit";

export type JobProgress = { completed: number, total?: number, unit: ProgressUnit, };
