// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JobState = "queued" | "preparing" | "running" | "pause_requested" | "paused" | "cancel_requested" | "recovering" | "finalizing" | "completed" | "cancelled" | "failed";
