// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenerationStage } from "./GenerationStage";
import type { JobError } from "./JobError";
import type { JobProgress } from "./JobProgress";
import type { JobState } from "./JobState";

export type JobView = { id: string, revision: number, state: JobState, stage?: GenerationStage, progress?: JobProgress, model: string, created_at: string, updated_at: string, error?: JobError, };
