// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JobView = { id: string, state: string, stage: string, step: number | null, steps_total: number | null, };
