// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryChangeKind } from "./LibraryChangeKind";
import type { SongHeader } from "./SongHeader";

export type LibraryChange = { revision: number, song_id: string, kind: LibraryChangeKind, changed_at: string, song?: SongHeader, };
