// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LyricsCapabilities = { can_generate: boolean, requires_lyrics: boolean, instrumental_text?: string, writer_label?: string, };
