// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One control an engine declares.
 *
 * `key` is the field name the engine itself expects in its JSON input. The app
 * never translates a family or a selector into a field name -- that is the
 * whole point of declaring them.
 */
export type ModelParameter = { "kind": "integer", key: string, label: string, default: number, minimum: number, maximum: number, step?: number, } | { "kind": "number", key: string, label: string, default: number, minimum: number, maximum: number, step?: number, } | { "kind": "boolean", key: string, label: string, default: boolean, } | { "kind": "choice", key: string, label: string, default: string, 
/**
 * Ordered; the app shows them in this order and does not sort.
 */
choices: Array<string>, } | { "kind": "text", key: string, label: string, default: string, max_bytes: number, };
