// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelView = { 
/**
 * Stable value accepted by `job.create`, for example `acestep:1.5-fast`.
 */
selector: string, family: string, engine: string, };
