// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenerationStage } from "./GenerationStage";
import type { LyricsCapabilities } from "./LyricsCapabilities";
import type { ModelParameter } from "./ModelParameter";

export type ModelView = { 
/**
 * Stable value accepted by `job.create`, for example `acestep:1.5-fast`.
 */
selector: string, family: string, engine: string, 
/**
 * The stages this model actually runs, in order.
 *
 * `None` means the node has not declared them -- an older node, or a
 * marker written before declarations existed. That is different from
 * declaring none, and clients draw observed stages rather than guessing an
 * arc when it is absent.
 */
stages?: Array<GenerationStage>, 
/**
 * Controls this model accepts beyond caption, lyrics and duration.
 */
parameters?: Array<ModelParameter>, lyrics?: LyricsCapabilities, };
