// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactView } from "./ArtifactView";
import type { ErrorCode } from "./ErrorCode";
import type { ErrorDetails } from "./ErrorDetails";
import type { JobView } from "./JobView";
import type { LibraryChange } from "./LibraryChange";
import type { NodeInfo } from "./NodeInfo";
import type { SongDetail } from "./SongDetail";
import type { SongHeader } from "./SongHeader";

export type NodeMessage = { "t": "challenge", v: number, id: string, nonce: string, node_pubkey: string, } | { "t": "welcome", v: number, id: string, node: NodeInfo, } | { "t": "job.accepted", v: number, id: string, job: JobView, } | { "t": "jobs.page", v: number, id: string, jobs: Array<JobView>, next_cursor?: string, } | { "t": "job.detail", v: number, id: string, job: JobView, } | { "t": "job.updated", v: number, job: JobView, } | { "t": "job.controlled", v: number, id: string, job: JobView, } | { "t": "job.forgotten", v: number, id?: string, job_id: string, } | { "t": "library.page", v: number, id: string, snapshot_revision: number, songs: Array<SongHeader>, tombstones: Array<string>, next_cursor?: string, } | { "t": "library.changes", v: number, id: string, through_revision: number, changes: Array<LibraryChange>, has_more: boolean, } | { "t": "song.detail", v: number, id: string, detail: SongDetail, } | { "t": "song.updated", v: number, id: string, song: SongHeader, } | { "t": "artifact.info", v: number, id: string, transfer_id: string, song_id: string, artifact: ArtifactView, accepted_offset: number, chunk_bytes: number, window_chunks: number, } | { "t": "artifact.chunk", v: number, id: string, transfer_id: string, offset: number, data: string, } | { "t": "artifact.complete", v: number, id: string, transfer_id: string, byte_length: number, sha256: string, } | { "t": "library.changed", v: number, revision: number, } | { "t": "error", v: number, id?: string, code: ErrorCode, message: string, retryable: boolean, details?: ErrorDetails, } | { "t": "node.info", v: number, node: NodeInfo, };
