// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NodeFeatures = { jobs_create: boolean, library_list: boolean, artifacts_transfer: boolean, secure_tunnel: boolean, job_controls: boolean, };
