// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from "./ErrorCode";
import type { ErrorDetails } from "./ErrorDetails";
import type { JobView } from "./JobView";
import type { NodeInfo } from "./NodeInfo";

export type NodeMessage = { "t": "challenge", v: number, id: string, nonce: string, node_pubkey: string, } | { "t": "welcome", v: number, id: string, node: NodeInfo, } | { "t": "job.accepted", v: number, id: string, job: JobView, } | { "t": "jobs.page", v: number, id: string, jobs: Array<JobView>, next_cursor?: string, } | { "t": "job.detail", v: number, id: string, job: JobView, } | { "t": "job.updated", v: number, job: JobView, } | { "t": "error", v: number, id?: string, code: ErrorCode, message: string, retryable: boolean, details?: ErrorDetails, } | { "t": "node.info", v: number, node: NodeInfo, };
