// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeLimits } from "./NodeLimits";
import type { NodeLoad } from "./NodeLoad";

export type NodeInfo = { name: string, device_type: string, engine_version: string, models: Array<string>, limits: NodeLimits, load: NodeLoad, };
