// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NodeLimits = { max_concurrent_jobs: number, max_queued_jobs_per_principal: number, min_song_seconds: number, max_song_seconds: number, max_caption_bytes: number, max_lyrics_bytes: number, max_page_limit: number, };
