// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A scalar an engine parameter can carry. Scalars only: an engine field is a
 * value, not a structure, and allowing nesting would make validation open.
 */
export type ParameterValue = boolean | number | string;
