// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenerationRequest } from "./GenerationRequest";
import type { SongHeader } from "./SongHeader";

export type SongDetail = { song: SongHeader, generation: GenerationRequest, engine: string, component_digests: Array<string>, attempts: number, };
