// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactView } from "./ArtifactView";

export type SongHeader = { id: string, revision: number, title: string, caption_summary: string, created_at: string, duration_ms: number, model: string, seed?: number | undefined, favorite: boolean, tags: Array<string>, trashed: boolean, artifacts: Array<ArtifactView>, };
