// @generated by protocol/transport/generate.mjs from protocol/transport/v1/spec.json.
// DO NOT EDIT; run node protocol/transport/generate.mjs.

export const APPLICATION_PROTOCOL_VERSION = 2 as const;
export const APPLICATION_PROTOCOL_MIN_SUPPORTED_VERSION = 2 as const;
export const APPLICATION_PROTOCOL_MAX_SUPPORTED_VERSION = 2 as const;
export const RELAY_PROTOCOL_VERSION = 1 as const;
export const SECURE_NEGOTIATION_VERSION = 1 as const;
export const TRANSPORT_DESCRIPTOR_VERSION = 1 as const;
export const SECURE_CARRIER_VERSION = 1 as const;
export const SECURE_RECORD_VERSION = 1 as const;
export const SECURE_INNER_VERSION = 1 as const;

export const NOISE_PROTOCOL_NAME = "Noise_NK_25519_ChaChaPoly_SHA256" as const;
export const TRANSPORT_SUITE_ID = "noise-nk-25519-chachapoly-sha256-v1" as const;
export const NOISE_AUTHENTICATION_TAG_BYTES = 16 as const;

export const TRANSPORT_DESCRIPTOR_SIGNATURE_DOMAIN = "cantor-transport-binding-v1" as const;
export const SECURE_HANDSHAKE_PROLOGUE_DOMAIN = "cantor-secure-channel-v1" as const;

export const SECURE_CARRIER_KIND = 1 as const;
export const FRAGMENT_RECORD_KIND = 1 as const;
export const CONTROL_INNER_KIND = 1 as const;
export const ARTIFACT_CHUNK_INNER_KIND = 2 as const;

export const CLIENT_CARRIER_HEADER_BYTES = 6 as const;
export const NODE_CARRIER_FIXED_HEADER_BYTES = 8 as const;
export const FRAGMENT_RECORD_HEADER_BYTES = 18 as const;
export const CONTROL_INNER_HEADER_BYTES = 6 as const;
export const ARTIFACT_INNER_FIXED_HEADER_BYTES = 18 as const;

export const ED25519_PUBLIC_KEY_BYTES = 32 as const;
export const ED25519_SIGNATURE_BYTES = 64 as const;
export const X25519_KEY_BYTES = 32 as const;
export const SHA256_DIGEST_BYTES = 32 as const;
export const CHANNEL_NONCE_BYTES = 32 as const;

export const MAX_RELAY_SESSION_ID_UTF8_BYTES = 64 as const;
export const MAX_HANDSHAKE_MESSAGE_BYTES = 4096 as const;
export const MAX_NOISE_PLAINTEXT_BYTES = 61440 as const;
export const MAX_SECURE_CIPHERTEXT_BYTES = 98304 as const;
export const MAX_LOGICAL_INNER_BYTES = 1048576 as const;
export const ARTIFACT_CHUNK_BYTES = 65536 as const;
export const MAX_ARTIFACT_IDENTIFIER_UTF8_BYTES = 256 as const;
export const MAX_ARTIFACT_OFFSET_SAFE_INTEGER = 9007199254740991 as const;
export const MAX_SESSION_RECORDS_PER_DIRECTION = 1000000 as const;
export const MAX_SESSION_CIPHERTEXT_BYTES_PER_DIRECTION = 1073741824 as const;

export const MAX_FRAGMENT_DATA_BYTES = 61422 as const;
export const SHA256_HEX_CHARS = 64 as const;
export const EXPECTED_PROLOGUE_BYTES = 123 as const;
