// @generated by protocol/transport/generate.mjs from protocol/transport/v1/spec.json.
// DO NOT EDIT; run node protocol/transport/generate.mjs.

pub(crate) const RELAY_PROTOCOL_VERSION: u8 = 1;
pub(crate) const SECURE_NEGOTIATION_VERSION: u8 = 1;
pub(crate) const TRANSPORT_DESCRIPTOR_VERSION: u8 = 1;
pub(crate) const SECURE_CARRIER_VERSION: u8 = 1;
pub(crate) const SECURE_RECORD_VERSION: u8 = 1;
pub(crate) const SECURE_INNER_VERSION: u8 = 1;

pub(crate) const NOISE_PROTOCOL_NAME: &str = "Noise_NK_25519_ChaChaPoly_SHA256";
pub(crate) const TRANSPORT_SUITE_ID: &str = "noise-nk-25519-chachapoly-sha256-v1";
pub(crate) const NOISE_AUTHENTICATION_TAG_BYTES: usize = 16;

pub(crate) const TRANSPORT_DESCRIPTOR_SIGNATURE_DOMAIN: &[u8] = b"cantor-transport-binding-v1";
pub(crate) const SECURE_HANDSHAKE_PROLOGUE_DOMAIN: &[u8] = b"cantor-secure-channel-v1";

pub(crate) const SECURE_CARRIER_KIND: u8 = 1;
pub(crate) const FRAGMENT_RECORD_KIND: u8 = 1;
pub(crate) const CONTROL_INNER_KIND: u8 = 1;
pub(crate) const ARTIFACT_CHUNK_INNER_KIND: u8 = 2;

pub(crate) const CLIENT_CARRIER_HEADER_BYTES: usize = 6;
pub(crate) const NODE_CARRIER_FIXED_HEADER_BYTES: usize = 8;
pub(crate) const FRAGMENT_RECORD_HEADER_BYTES: usize = 18;
pub(crate) const CONTROL_INNER_HEADER_BYTES: usize = 6;
pub(crate) const ARTIFACT_INNER_FIXED_HEADER_BYTES: usize = 18;

pub(crate) const ED25519_PUBLIC_KEY_BYTES: usize = 32;
pub(crate) const ED25519_SIGNATURE_BYTES: usize = 64;
pub(crate) const X25519_KEY_BYTES: usize = 32;
pub(crate) const SHA256_DIGEST_BYTES: usize = 32;
pub(crate) const CHANNEL_NONCE_BYTES: usize = 32;

pub(crate) const MAX_RELAY_SESSION_ID_UTF8_BYTES: usize = 64;
pub(crate) const MAX_HANDSHAKE_MESSAGE_BYTES: usize = 4_096;
pub(crate) const MAX_NOISE_PLAINTEXT_BYTES: usize = 61_440;
pub(crate) const MAX_SECURE_CIPHERTEXT_BYTES: usize = 98_304;
pub(crate) const MAX_LOGICAL_INNER_BYTES: usize = 1_048_576;
pub(crate) const MAX_ARTIFACT_IDENTIFIER_UTF8_BYTES: usize = 256;
pub(crate) const MAX_ARTIFACT_OFFSET_SAFE_INTEGER: u64 = 9_007_199_254_740_991;
pub(crate) const MAX_SESSION_RECORDS_PER_DIRECTION: u64 = 1_000_000;
pub(crate) const MAX_SESSION_CIPHERTEXT_BYTES_PER_DIRECTION: u64 = 1_073_741_824;

pub(crate) const MAX_FRAGMENT_DATA_BYTES: usize = 61_422;
pub(crate) const SHA256_HEX_CHARS: usize = 64;
pub(crate) const EXPECTED_PROLOGUE_BYTES: usize = 123;
