package com.cantor.app.transport

// @generated by protocol/transport/generate.mjs from protocol/transport/v1/spec.json.
// DO NOT EDIT; run node protocol/transport/generate.mjs.
internal object GeneratedTransport {
  const val SECURE_RECORD_VERSION: Byte = 1
  const val NOISE_PROTOCOL_NAME: String = "Noise_NK_25519_ChaChaPoly_SHA256"
  const val NOISE_AUTHENTICATION_TAG_BYTES: Int = 16
  const val FRAGMENT_RECORD_KIND: Byte = 1
  const val FRAGMENT_RECORD_HEADER_BYTES: Int = 18
  const val X25519_KEY_BYTES: Int = 32
  const val MAX_HANDSHAKE_MESSAGE_BYTES: Int = 4_096
  const val MAX_NOISE_PLAINTEXT_BYTES: Int = 61_440
  const val MAX_SECURE_CIPHERTEXT_BYTES: Int = 98_304
  const val MAX_LOGICAL_INNER_BYTES: Int = 1_048_576
  const val ARTIFACT_CHUNK_BYTES: Int = 65_536
  const val MAX_SESSION_RECORDS_PER_DIRECTION: Long = 1_000_000L
  const val MAX_SESSION_CIPHERTEXT_BYTES_PER_DIRECTION: Long = 1_073_741_824L
  const val MAX_FRAGMENT_DATA_BYTES: Int = 61_422
  const val EXPECTED_PROLOGUE_BYTES: Int = 123
}
