import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, resolve } from 'node:path';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';

import {
  OUTPUT_PATHS,
  checkRendered,
  deriveConstants,
  loadValidate,
  renderAll,
  validateSpec,
  writeRendered,
} from './generate.mjs';

const REPOSITORY_ROOT = fileURLToPath(new URL('../../', import.meta.url));

/** The committed manifest, reloaded per test so mutations never leak. */
async function committedSpec() {
  return loadValidate();
}

test('the committed manifest is valid and names the deployed constants', async () => {
  const spec = await committedSpec();
  assert.equal(spec.contract, 'cantor-transport');
  assert.equal(spec.byte_order, 'big-endian');
  assert.equal(spec.versions.application_current, 2);
  assert.equal(spec.noise.protocol_name, 'Noise_NK_25519_ChaChaPoly_SHA256');
  assert.equal(spec.noise.suite_id, 'noise-nk-25519-chachapoly-sha256-v1');
  assert.equal(
    spec.domains.transport_descriptor_signature,
    'cantor-transport-binding-v1',
  );
  assert.equal(spec.domains.secure_handshake_prologue, 'cantor-secure-channel-v1');
});

test('derived constants match the deployed byte arithmetic', async () => {
  const derived = deriveConstants(await committedSpec());
  assert.equal(derived.maxFragmentDataBytes, 60 * 1024 - 18);
  assert.equal(derived.sha256HexChars, 64);
  // 24 domain bytes + u16 application version + u8 carrier version + 3 keys.
  assert.equal(derived.expectedPrologueBytes, 123);
});

test('every layer version is independent even where the value is one', async () => {
  const spec = await committedSpec();
  spec.versions.secure_inner = 3;
  const derived = deriveConstants(spec);
  const rendered = renderAll(spec);
  assert.match(
    rendered[OUTPUT_PATHS.rustNode],
    /SECURE_INNER_VERSION: u8 = 3;/,
  );
  assert.match(
    rendered[OUTPUT_PATHS.rustNode],
    /SECURE_CARRIER_VERSION: u8 = 1;/,
  );
  assert.equal(derived.expectedPrologueBytes, 123);
});

test('rendering is deterministic and covers every target language', async () => {
  const spec = await committedSpec();
  const first = renderAll(spec);
  const second = renderAll(await committedSpec());
  assert.deepEqual(Object.keys(first).sort(), Object.values(OUTPUT_PATHS).sort());
  for (const path of Object.values(OUTPUT_PATHS)) {
    assert.equal(first[path], second[path], `${path} must be deterministic`);
    assert.match(first[path], /@generated by protocol\/transport\/generate\.mjs/);
    assert.match(first[path], /DO NOT EDIT/);
  }
  assert.match(first[OUTPUT_PATHS.androidKotlin], /^package com\.cantor\.app\.transport/);
});

test('the checked-in generated files are current', async () => {
  const stale = await checkRendered(renderAll(await committedSpec()));
  assert.deepEqual(
    stale,
    [],
    'run: node protocol/transport/generate.mjs',
  );
});

test('a hand-edited generated file is reported as stale', async () => {
  const spec = await committedSpec();
  const rendered = renderAll(spec);
  const root = await mkdtemp(resolve(tmpdir(), 'cantor-transport-'));
  await writeRendered(rendered, root);
  assert.deepEqual(await checkRendered(rendered, root), []);

  const target = resolve(root, OUTPUT_PATHS.relayTypeScript);
  await writeFile(target, `${await readFile(target, 'utf8')}// edited\n`);
  assert.deepEqual(await checkRendered(rendered, root), [
    OUTPUT_PATHS.relayTypeScript,
  ]);

  await writeRendered(rendered, root);
  assert.deepEqual(await checkRendered(rendered, root), []);
});

test('a missing generated file is reported as stale', async () => {
  const rendered = renderAll(await committedSpec());
  const root = await mkdtemp(resolve(tmpdir(), 'cantor-transport-'));
  await mkdir(dirname(resolve(root, OUTPUT_PATHS.rustProto)), { recursive: true });
  assert.deepEqual(
    (await checkRendered(rendered, root)).sort(),
    Object.values(OUTPUT_PATHS).sort(),
  );
});

test('structural manifest mistakes fail before anything is generated', async () => {
  const mutations = [
    ['an unknown root key', spec => (spec.extra = 1)],
    ['a missing section', spec => delete spec.kinds],
    ['a foreign contract', spec => (spec.contract = 'other')],
    ['a little-endian claim', spec => (spec.byte_order = 'little-endian')],
    ['a zero version', spec => (spec.versions.relay = 0)],
    ['a non-integer bound', spec => (spec.bounds.handshake_message_bytes = 1.5)],
    ['an empty domain label', spec => (spec.domains.secure_handshake_prologue = '')],
    [
      'unordered application versions',
      spec => (spec.versions.application_min_supported = 3),
    ],
    [
      'colliding inner kinds',
      spec => (spec.kinds.artifact_chunk_inner = spec.kinds.control_inner),
    ],
    ['a header that contradicts its fields', spec => (spec.headers.control_inner_bytes = 7)],
    [
      'a session id that overflows its u16 field',
      spec => (spec.bounds.relay_session_id_utf8_bytes = 0x1_0000),
    ],
    [
      'a ciphertext bound below plaintext plus tag',
      spec => (spec.bounds.secure_ciphertext_bytes = spec.bounds.noise_plaintext_bytes),
    ],
    [
      'an artifact chunk that cannot hold its header',
      spec => (spec.bounds.artifact_chunk_bytes = spec.bounds.logical_inner_bytes),
    ],
  ];
  for (const [description, mutate] of mutations) {
    const spec = await committedSpec();
    mutate(spec);
    assert.throws(
      () => validateSpec(spec),
      error => error instanceof TypeError,
      `${description} must be rejected`,
    );
  }
});

test('the generator refuses unknown command line arguments', async () => {
  const { spawnSync } = await import('node:child_process');
  const script = fileURLToPath(new URL('generate.mjs', import.meta.url));
  const result = spawnSync(process.execPath, [script, '--write-everything'], {
    cwd: REPOSITORY_ROOT,
    encoding: 'utf8',
  });
  assert.equal(result.status, 1);
  assert.match(result.stderr, /usage: node protocol\/transport\/generate\.mjs/);
});
