/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f8ad1eda624db0e232bbd4931b3d83cf)
interface __BaseEnv_Env {
	ROOMS: DurableObjectNamespace<import("./src/index").NodeRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "NodeRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
declare module "*.sh" {
	const value: string;
	export default value;
}