/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: da0d6210d5a14b6c0c8e7913c937c5f2)
interface __BaseEnv_Env {
	ROOMS: DurableObjectNamespace<import("./src/index").NodeRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "NodeRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
